version: "3"
services:
  frontend:
    build:
      context: ./billing-state-frontend
      dockerfile:
        - Dockerfile.prod # For production
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./billing-state-backend
      dockerfile:
        - Dockerfile.prod # For production
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
