version: "3.9"
services:
  frontend:
    build:
      context: ./billing-state-frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./billing-state-backend/
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    env_file:
      - ./billing-state-backend/src/config/config.env

  mongodb:
    image: mongo:4.4.6
    volumes:
      - mongo_db:/data/db
    ports:
      - 27018:27017
volumes:
  mongo_db:
