# Use the official Node.js 14 image as the base
FROM node:18

# Set the working directory in the container
WORKDIR /app/billing-state-frontend

# Copy the package.json and yarn.lock files to the container
COPY package*.json yarn.lock ./

# Install Yarn globally
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Install project dependencies using Yarn
RUN yarn --verbose

COPY . .

# Expose the port on which the backend server will run
EXPOSE 3000

# Start the backend server
CMD ["yarn","run","dev"]
