FROM node:18

# Set the working directory in the container
WORKDIR /app/billing-state-backend

# Copy the package.json and yarn.lock files to the container
COPY package*.json yarn.lock ./

# Install Yarn globally
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

RUN yarn cache clean

RUN yarn add -D nodemon

# Install project dependencies using Yarn

COPY . .

RUN yarn  --verbose

# Expose the port on which the backend server will run
EXPOSE 5000

# Start the backend server
CMD ["yarn","run","dev"]
