# Use the official Node.js 14 image as the base
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY billing-state-backend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the backend application code to the container
COPY billing-state-backend ./

# Expose the port on which the backend server will run
EXPOSE 5000

# Start the backend server
CMD ["npm", "start"]
